// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facePass.proto

package com.kk.grpc.bean;

public interface ClientResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:facePass.ClientResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string data = 1;</code>
   */
  String getData();
  /**
   * <code>optional string data = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
