// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facePass.proto

package com.kk.grpc.bean;

public final class FacePassProtos {
  private FacePassProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
