package com.eyecool.visitorsys.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.eyecool.visitor.sys.bean.CustomerInfo;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CUSTOMER_INFO".
*/
public class CustomerInfoDao extends AbstractDao<CustomerInfo, Long> {

    public static final String TABLENAME = "CUSTOMER_INFO";

    /**
     * Properties of entity CustomerInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, String.class, "user_id", false, "USER_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Phone = new Property(3, String.class, "phone", false, "PHONE");
        public final static Property User_type = new Property(4, String.class, "user_type", false, "USER_TYPE");
        public final static Property St_class = new Property(5, String.class, "st_class", false, "ST_CLASS");
        public final static Property Position = new Property(6, String.class, "position", false, "POSITION");
        public final static Property Bespoke = new Property(7, String.class, "bespoke", false, "BESPOKE");
        public final static Property Feature_value = new Property(8, String.class, "feature_value", false, "FEATURE_VALUE");
        public final static Property Feature_img = new Property(9, String.class, "feature_img", false, "FEATURE_IMG");
        public final static Property Stu_teacher = new Property(10, String.class, "stu_teacher", false, "STU_TEACHER");
        public final static Property Visitor_stu = new Property(11, String.class, "visitor_stu", false, "VISITOR_STU");
        public final static Property Visitor_stu_gender = new Property(12, String.class, "visitor_stu_gender", false, "VISITOR_STU_GENDER");
        public final static Property Visitor_stu_img_path = new Property(13, String.class, "visitor_stu_img_path", false, "VISITOR_STU_IMG_PATH");
        public final static Property Card_id = new Property(14, String.class, "card_id", false, "CARD_ID");
        public final static Property Remark = new Property(15, String.class, "remark", false, "REMARK");
    };


    public CustomerInfoDao(DaoConfig config) {
        super(config);
    }
    
    public CustomerInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CUSTOMER_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_ID\" TEXT," + // 1: user_id
                "\"NAME\" TEXT," + // 2: name
                "\"PHONE\" TEXT," + // 3: phone
                "\"USER_TYPE\" TEXT," + // 4: user_type
                "\"ST_CLASS\" TEXT," + // 5: st_class
                "\"POSITION\" TEXT," + // 6: position
                "\"BESPOKE\" TEXT," + // 7: bespoke
                "\"FEATURE_VALUE\" TEXT," + // 8: feature_value
                "\"FEATURE_IMG\" TEXT," + // 9: feature_img
                "\"STU_TEACHER\" TEXT," + // 10: stu_teacher
                "\"VISITOR_STU\" TEXT," + // 11: visitor_stu
                "\"VISITOR_STU_GENDER\" TEXT," + // 12: visitor_stu_gender
                "\"VISITOR_STU_IMG_PATH\" TEXT," + // 13: visitor_stu_img_path
                "\"CARD_ID\" TEXT," + // 14: card_id
                "\"REMARK\" TEXT);"); // 15: remark
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CUSTOMER_INFO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CustomerInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(2, user_id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(4, phone);
        }
 
        String user_type = entity.getUser_type();
        if (user_type != null) {
            stmt.bindString(5, user_type);
        }
 
        String st_class = entity.getSt_class();
        if (st_class != null) {
            stmt.bindString(6, st_class);
        }
 
        String position = entity.getPosition();
        if (position != null) {
            stmt.bindString(7, position);
        }
 
        String bespoke = entity.getBespoke();
        if (bespoke != null) {
            stmt.bindString(8, bespoke);
        }
 
        String feature_value = entity.getFeature_value();
        if (feature_value != null) {
            stmt.bindString(9, feature_value);
        }
 
        String feature_img = entity.getFeature_img();
        if (feature_img != null) {
            stmt.bindString(10, feature_img);
        }
 
        String stu_teacher = entity.getStu_teacher();
        if (stu_teacher != null) {
            stmt.bindString(11, stu_teacher);
        }
 
        String visitor_stu = entity.getVisitor_stu();
        if (visitor_stu != null) {
            stmt.bindString(12, visitor_stu);
        }
 
        String visitor_stu_gender = entity.getVisitor_stu_gender();
        if (visitor_stu_gender != null) {
            stmt.bindString(13, visitor_stu_gender);
        }
 
        String visitor_stu_img_path = entity.getVisitor_stu_img_path();
        if (visitor_stu_img_path != null) {
            stmt.bindString(14, visitor_stu_img_path);
        }
 
        String card_id = entity.getCard_id();
        if (card_id != null) {
            stmt.bindString(15, card_id);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(16, remark);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CustomerInfo readEntity(Cursor cursor, int offset) {
        CustomerInfo entity = new CustomerInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // user_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // phone
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // user_type
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // st_class
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // position
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // bespoke
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // feature_value
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // feature_img
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // stu_teacher
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // visitor_stu
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // visitor_stu_gender
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // visitor_stu_img_path
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // card_id
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15) // remark
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CustomerInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPhone(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUser_type(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSt_class(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPosition(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBespoke(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setFeature_value(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setFeature_img(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setStu_teacher(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setVisitor_stu(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setVisitor_stu_gender(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setVisitor_stu_img_path(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setCard_id(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setRemark(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CustomerInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CustomerInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
