package com.eyecool.visitor.sys.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "CUSTOMER_INFO".
 */
public class CustomerInfo implements Parcelable{

    private Long id;
    private String user_id;
    private String name;
    private String phone;
    private String user_type;
    private String st_class;
    private String position;
    private String bespoke;
    private String feature_value;
    private String feature_img;
    private String stu_teacher;
    private String visitor_stu;
    private String visitor_stu_gender;
    private String visitor_stu_img_path;
    private String card_id;
    private String remark;

    public CustomerInfo() {
    }

    public CustomerInfo(Long id) {
        this.id = id;
    }

    public CustomerInfo(Long id, String user_id, String name, String phone, String user_type, String st_class, String position, String bespoke, String feature_value, String feature_img, String stu_teacher, String visitor_stu, String visitor_stu_gender, String visitor_stu_img_path, String card_id, String remark) {
        this.id = id;
        this.user_id = user_id;
        this.name = name;
        this.phone = phone;
        this.user_type = user_type;
        this.st_class = st_class;
        this.position = position;
        this.bespoke = bespoke;
        this.feature_value = feature_value;
        this.feature_img = feature_img;
        this.stu_teacher = stu_teacher;
        this.visitor_stu = visitor_stu;
        this.visitor_stu_gender = visitor_stu_gender;
        this.visitor_stu_img_path = visitor_stu_img_path;
        this.card_id = card_id;
        this.remark = remark;
    }

    protected CustomerInfo(Parcel in){
        user_id = in.readString();
        name = in.readString();
        phone = in.readString();
        user_type = in.readString();
        st_class = in.readString();
        position = in.readString();
        bespoke = in.readString();
        feature_value = in.readString();
        feature_img = in.readString();
        stu_teacher = in.readString();
        visitor_stu = in.readString();
        visitor_stu_gender = in.readString();
        visitor_stu_img_path = in.readString();
        card_id = in.readString();
        remark = in.readString();
    }

    public static final Creator<CustomerInfo> CREATOR = new Creator<CustomerInfo>() {
        @Override
        public CustomerInfo createFromParcel(Parcel source) {
            return new CustomerInfo(source);
        }

        @Override
        public CustomerInfo[] newArray(int size) {
            return new CustomerInfo[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {

        dest.writeString(user_id);
        dest.writeString(name);
        dest.writeString(phone);
        dest.writeString(user_type);
        dest.writeString(st_class);
        dest.writeString(position);
        dest.writeString(bespoke);
        dest.writeString(feature_value);
        dest.writeString(feature_img);
        dest.writeString(stu_teacher);
        dest.writeString(visitor_stu);
        dest.writeString(visitor_stu_gender);
        dest.writeString(visitor_stu_img_path);
        dest.writeString(card_id);
        dest.writeString(remark);
    }

    public void readFromParcel(Parcel in){
        user_id = in.readString();
        name = in.readString();
        phone = in.readString();
        user_type = in.readString();
        st_class = in.readString();
        position = in.readString();
        bespoke = in.readString();
        feature_value = in.readString();
        feature_img = in.readString();
        stu_teacher = in.readString();
        visitor_stu = in.readString();
        visitor_stu_gender = in.readString();
        visitor_stu_img_path = in.readString();
        card_id = in.readString();
        remark = in.readString();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getUser_type() {
        return user_type;
    }

    public void setUser_type(String user_type) {
        this.user_type = user_type;
    }

    public String getSt_class() {
        return st_class;
    }

    public void setSt_class(String st_class) {
        this.st_class = st_class;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getBespoke() {
        return bespoke;
    }

    public void setBespoke(String bespoke) {
        this.bespoke = bespoke;
    }

    public String getFeature_value() {
        return feature_value;
    }

    public void setFeature_value(String feature_value) {
        this.feature_value = feature_value;
    }

    public String getFeature_img() {
        return feature_img;
    }

    public void setFeature_img(String feature_img) {
        this.feature_img = feature_img;
    }

    public String getStu_teacher() {
        return stu_teacher;
    }

    public void setStu_teacher(String stu_teacher) {
        this.stu_teacher = stu_teacher;
    }

    public String getVisitor_stu() {
        return visitor_stu;
    }

    public void setVisitor_stu(String visitor_stu) {
        this.visitor_stu = visitor_stu;
    }

    public String getVisitor_stu_gender() {
        return visitor_stu_gender;
    }

    public void setVisitor_stu_gender(String visitor_stu_gender) {
        this.visitor_stu_gender = visitor_stu_gender;
    }

    public String getVisitor_stu_img_path() {
        return visitor_stu_img_path;
    }

    public void setVisitor_stu_img_path(String visitor_stu_img_path) {
        this.visitor_stu_img_path = visitor_stu_img_path;
    }

    public String getCard_id() {
        return card_id;
    }

    public void setCard_id(String card_id) {
        this.card_id = card_id;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }


}
